#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tutorial
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tutorial_test
  pool: 5
  username: root
  password:
  host: localhost
